import { z } from "zod";

// Shape of the structured portfolio artifact the data tools read from.
// Eventually generated by the Notion Projects-database sync (see issue #5);
// until then it's a local file (knowledge/portfolio.json, gitignored like
// the knowledge base) with a committed placeholder example.
export const PortfolioDataSchema = z.object({
  contact: z.object({
    email: z.string(),
    linkedin: z.string(),
    github: z.string(),
  }),
  projects: z
    .array(
      z.object({
        id: z.string(),
        name: z.string(),
        summary: z.string(),
        technologies: z.array(z.string()).default([]),
        tags: z.array(z.string()).default([]),
        links: z.record(z.string(), z.string()).default({}),
      }),
    )
    .default([]),
});

export type PortfolioData = z.infer<typeof PortfolioDataSchema>;
